# Assignment 4
_The following file is for Assignment 4 for the Course "Introduction to Data Science" from Michigan University on the Coursera platform_
## Description
In this assignment you must read in a file of metropolitan regions and associated sports teams from [assets/wikipedia_data.html](assets/wikipedia_data.html) and answer some questions about each metropolitan region. Each of these regions may have one or more teams from the "Big 4": NFL (football, in [assets/nfl.csv](assets/nfl.csv)), MLB (baseball, in [assets/mlb.csv](assets/mlb.csv)), NBA (basketball, in [assets/nba.csv](assets/nba.csv) or NHL (hockey, in [assets/nhl.csv](assets/nhl.csv)). Please keep in mind that all questions are from the perspective of the metropolitan region, and that this file is the "source of authority" for the location of a given sports team. Thus teams which are commonly known by a different area (e.g. "Oakland Raiders") need to be mapped into the metropolitan region given (e.g. San Francisco Bay Area). This will require some human data understanding outside of the data you've been given (e.g. you will have to hand-code some names, and might need to google to find out where teams are)!

For each sport I would like you to answer the question: **what is the win/loss ratio's correlation with the population of the city it is in?** Win/Loss ratio refers to the number of wins over the number of wins plus the number of losses. Remember that to calculate the correlation with [`pearsonr`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html), so you are going to send in two ordered lists of values, the populations from the wikipedia_data.html file and the win/loss ratio for a given sport in the same order. Average the win/loss ratios for those cities which have multiple teams of a single sport. Each sport is worth an equal amount in this assignment (20%\*4=80%) of the grade for this assignment. You should only use data **from year 2018** for your analysis -- this is important!

## Notes

1. Do not include data about the MLS or CFL in any of the work you are doing, we're only interested in the Big 4 in this assignment.
2. I highly suggest that you first tackle the four correlation questions in order, as they are all similar and worth the majority of grades for this assignment. This is by design!
3. It's fair game to talk with peers about high level strategy as well as the relationship between metropolitan areas and sports teams. However, do not post code solving aspects of the assignment (including such as dictionaries mapping areas to teams, or regexes which will clean up names).
4. There may be more teams than the assert statements test, remember to collapse multiple teams in one city into a single value!'

### Question 1
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NHL** using **2018** data.

In [1]:
#For all exercises you should import the librarias in the function according to coursera laboratory platform, but in this case i will not use a function for each question, I only import the libs once

#import libraries
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

In [2]:
# Load the databases
NHL_df = pd.read_csv("assets/nhl.csv")
cities = pd.read_html("assets/wikipedia_data.html")[1]
cities = cities.iloc[:-1,[0,3,5,6,7,8]]

In [3]:
#Cleaning NHL_df   
NHL_df = NHL_df[NHL_df['year'] == 2018]
NHL_df = NHL_df[['team','W','L']]
# Cleaning
def remover_star(team):
    if "*" in team:
        return re.findall("([\w\s]*)\*",team)[0]
    else:
        return team
    
NHL_df['team'] = NHL_df.team.apply(remover_star)
NHL_df['team_only'] = NHL_df.team.apply(lambda x: x.rsplit(None,1)[-1])
NHL_df

,team,W,L,team_only
0,Atlantic Division,Atlantic Division,Atlantic Division,Division
1,Tampa Bay Lightning,54,23,Lightning
2,Boston Bruins,50,20,Bruins
3,Toronto Maple Leafs,49,26,Leafs
4,Florida Panthers,44,30,Panthers
5,Detroit Red Wings,30,39,Wings
6,Montreal Canadiens,29,40,Canadiens
7,Ottawa Senators,28,43,Senators
8,Buffalo Sabres,25,45,Sabres
9,Metropolitan Division,Metropolitan Division,Metropolitan Division,Division
10,Washington Capitals,49,26,Capitals
11,Pittsburgh Penguins,47,29,Penguins
12,Philadelphia Flyers,42,26,Flyers
13,Columbus Blue Jackets,45,30,Jackets
14,New Jersey Devils,44,29,Devils
15,Carolina Hurricanes,36,35,Hurricanes
16,New York Islanders,35,37,Islanders
17,New York Rangers,34,39,Rangers
18,Central Division,Central Division,Central Division,Division
19,Nashville Predators,53,18,Predators
20,Winnipeg Jets,52,20,Jets
21,Minnesota Wild,45,26,Wild
22,Colorado Avalanche,43,30,Avalanche
23,St. Louis Blues,44,32,Blues
24,Dallas Stars,42,32,Stars
25,Chicago Blackhawks,33,39,Blackhawks
26,Pacific Division,Pacific Division,Pacific Division,Division
27,Vegas Golden Knights,51,24,Knights
28,Anaheim Ducks,44,25,Ducks
29,San Jose Sharks,45,27,Sharks
30,Los Angeles Kings,45,29,Kings
31,Calgary Flames,37,35,Flames
32,Edmonton Oilers,36,40,Oilers
33,Vancouver Canucks,31,40,Canucks
34,Arizona Coyotes,29,41,Coyotes

In [4]:
#Changing some team names, because in the datasets 'cities'
NHL_df.loc[3, 'team_only'] = 'Maple Leafs'
NHL_df.loc[5, 'team_only'] = 'Red Wings'
NHL_df.loc[13, 'team_only'] = 'Blue Jackets'
NHL_df.loc[27, 'team_only'] = 'Golden Knights'

NHL_df = NHL_df[~NHL_df.W.str.contains('Division')]
NHL_df = NHL_df.reset_index(drop=True)

NHL_df.loc[12, 'team_only'] = 'Rangers Islanders Devils'
NHL_df.loc[14, 'team_only'] = 'Rangers Islanders Devils'
NHL_df.loc[15, 'team_only'] = 'Rangers Islanders Devils'

NHL_df.loc[24, 'team_only'] = 'Kings Ducks'
NHL_df.loc[26, 'team_only'] = 'Kings Ducks'

NHL_df.W = NHL_df.W.astype(float)
NHL_df.L = NHL_df.L.astype(float)

#we have the 28 teams!!
NHL_df

                     team     W     L                 team_only
0     Tampa Bay Lightning  54.0  23.0                 Lightning
1           Boston Bruins  50.0  20.0                    Bruins
2     Toronto Maple Leafs  49.0  26.0               Maple Leafs
3        Florida Panthers  44.0  30.0                  Panthers
4       Detroit Red Wings  30.0  39.0                 Red Wings
5      Montreal Canadiens  29.0  40.0                 Canadiens
6         Ottawa Senators  28.0  43.0                  Senators
7          Buffalo Sabres  25.0  45.0                    Sabres
8     Washington Capitals  49.0  26.0                  Capitals
9     Pittsburgh Penguins  47.0  29.0                  Penguins
10    Philadelphia Flyers  42.0  26.0                    Flyers
11  Columbus Blue Jackets  45.0  30.0              Blue Jackets
12      New Jersey Devils  44.0  29.0  Rangers Islanders Devils
13    Carolina Hurricanes  36.0  35.0                Hurricanes
14     New York Islanders  35.0  37.0  Rangers Islanders Devils
15       New York Rangers  34.0  39.0  Rangers Islanders Devils
16    Nashville Predators  53.0  18.0                 Predators
17          Winnipeg Jets  52.0  20.0                      Jets
18         Minnesota Wild  45.0  26.0                      Wild
19     Colorado Avalanche  43.0  30.0                 Avalanche
20        St. Louis Blues  44.0  32.0                     Blues
21           Dallas Stars  42.0  32.0                     Stars
22     Chicago Blackhawks  33.0  39.0                Blackhawks
23   Vegas Golden Knights  51.0  24.0            Golden Knights
24          Anaheim Ducks  44.0  25.0               Kings Ducks
25        San Jose Sharks  45.0  27.0                    Sharks
26      Los Angeles Kings  45.0  29.0               Kings Ducks
27         Calgary Flames  37.0  35.0                    Flames
28        Edmonton Oilers  36.0  40.0                    Oilers
29      Vancouver Canucks  31.0  40.0                   Canucks
30        Arizona Coyotes  29.0  41.0                   Coyotes

In [5]:
#! Now Clean the Cities
def remove_bracket(team):
    if "[" in team:
        return re.findall("([\w\s]*)\[",team)[0]
    else:
        return team

cities['NHL'] = cities.NHL.apply(remove_bracket)

cities = cities [['Metropolitan area', 'Population (2016 est.)[8]','NHL']]

cities.rename(columns={'Metropolitan area':'city', 'Population (2016 est.)[8]':'population', 'NHL':'team_only'}, inplace=True)

cities['team_only'].unique()

array(['Rangers Islanders Devils', 'Kings Ducks', 'Sharks', 'Blackhawks',
       'Stars', 'Capitals', 'Flyers', 'Bruins', 'Wild', 'Avalanche',
       'Panthers', 'Coyotes', 'Red Wings', 'Maple Leafs', '—', '',
       'Lightning', 'Penguins', 'Blues', 'Predators', 'Sabres',
       'Canadiens', 'Canucks', 'Blue Jackets', 'Flames', 'Senators',
       'Oilers', 'Jets', 'Golden Knights', 'Hurricanes'], dtype=object)

In [6]:
NHL_df = NHL_df.groupby(by='team_only')['W','L'].mean()
NHL_df.reset_index(inplace=True)
NHL_df

C:\Users\Gamer\AppData\Local\Temp\ipykernel_15000\1823049277.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  NHL_df = NHL_df.groupby(by='team_only')['W','L'].mean()

                   team_only          W     L
0                  Avalanche  43.000000  30.0
1                 Blackhawks  33.000000  39.0
2               Blue Jackets  45.000000  30.0
3                      Blues  44.000000  32.0
4                     Bruins  50.000000  20.0
5                  Canadiens  29.000000  40.0
6                    Canucks  31.000000  40.0
7                   Capitals  49.000000  26.0
8                    Coyotes  29.000000  41.0
9                     Flames  37.000000  35.0
10                    Flyers  42.000000  26.0
11            Golden Knights  51.000000  24.0
12                Hurricanes  36.000000  35.0
13                      Jets  52.000000  20.0
14               Kings Ducks  44.500000  27.0
15                 Lightning  54.000000  23.0
16               Maple Leafs  49.000000  26.0
17                    Oilers  36.000000  40.0
18                  Panthers  44.000000  30.0
19                  Penguins  47.000000  29.0
20                 Predators  53.000000  18.0
21  Rangers Islanders Devils  37.666667  35.0
22                 Red Wings  30.000000  39.0
23                    Sabres  25.000000  45.0
24                  Senators  28.000000  43.0
25                    Sharks  45.000000  27.0
26                     Stars  42.000000  32.0
27                      Wild  45.000000  26.0

In [7]:
merge_df = pd.merge(NHL_df,cities,how='left', on='team_only')
merge_df

,team_only,W,L,city,population
0,Avalanche,43.000000,30.0,Denver,2853077
1,Blackhawks,33.000000,39.0,Chicago,9512999
2,Blue Jackets,45.000000,30.0,Columbus,2041520
3,Blues,44.000000,32.0,St. Louis,2807002
4,Bruins,50.000000,20.0,Boston,4794447
5,Canadiens,29.000000,40.0,Montreal,4098927
6,Canucks,31.000000,40.0,Vancouver,2463431
7,Capitals,49.000000,26.0,"Washington, D.C.",6131977
8,Coyotes,29.000000,41.0,Phoenix,4661537
9,Flames,37.000000,35.0,Calgary,1392609
10,Flyers,42.000000,26.0,Philadelphia,6070500
11,Golden Knights,51.000000,24.0,Las Vegas,2155664
12,Hurricanes,36.000000,35.0,Raleigh,1302946
13,Jets,52.000000,20.0,Winnipeg,778489
14,Kings Ducks,44.500000,27.0,Los Angeles,13310447
15,Lightning,54.000000,23.0,Tampa Bay Area,3032171
16,Maple Leafs,49.000000,26.0,Toronto,5928040
17,Oilers,36.000000,40.0,Edmonton,1321426
18,Panthers,44.000000,30.0,Miami–Fort Lauderdale,6066387
19,Penguins,47.000000,29.0,Pittsburgh,2342299
20,Predators,53.000000,18.0,Nashville,1865298
21,Rangers Islanders Devils,37.666667,35.0,New York City,20153634
22,Red Wings,30.000000,39.0,Detroit,4297617
23,Sabres,25.000000,45.0,Buffalo,1132804
24,Senators,28.000000,43.0,Ottawa,1323783
25,Sharks,45.000000,27.0,San Francisco Bay Area,6657982
26,Stars,42.000000,32.0,Dallas–Fort Worth,7233323
27,Wild,45.000000,26.0,Minneapolis–Saint Paul,3551036

In [8]:
merge_df['win_loss_ratio'] = merge_df.W / (merge_df.W + merge_df.L)

 #raise NotImplementedError()
    
population_by_region = pd.to_numeric(merge_df['population'],errors='coerce') # pass in metropolitan area population from cities
win_loss_by_region = pd.to_numeric(merge_df['win_loss_ratio'],errors='coerce') # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    
stats.pearsonr(population_by_region, win_loss_by_region)[0]

0.01230899645574427

### Question 2
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NBA** using **2018** data.

In [9]:
#The same process of cleaning but with NBA

# Load the databases
NBA_df = pd.read_csv("assets/nba.csv")
cities = pd.read_html("assets/wikipedia_data.html")[1]
cities = cities.iloc[:-1,[0,3,5,6,7,8]]
NBA_df = NBA_df[NBA_df.year == 2018]
NBA_df = NBA_df [['team', 'W', 'L']]

# Cleaning names

NBA_df['team'] = NBA_df.team.apply(lambda team: re.findall('([\w\s]*)\*',team)[0] if '*' in team else team)
NBA_df['team'] = NBA_df.team.apply(lambda team: re.findall('([\w\s]*)\(',team)[0] if '(' in team else team)

#Extract the team only
NBA_df['team_only'] = NBA_df.team.apply(lambda x: x.rsplit(None,1)[-1])

NBA_df.loc[10, 'team_only'] = 'Knicks Nets'
NBA_df.loc[11, 'team_only'] = 'Knicks Nets'

NBA_df.loc[24, 'team_only'] = 'Lakers Clippers'
NBA_df.loc[25, 'team_only'] = 'Lakers Clippers'

NBA_df.loc[17, 'team_only'] = 'Trail Blazers'

NBA_df.W = NBA_df.W.astype(float)
NBA_df.L = NBA_df.L.astype(float)

#The following command is because we need to combine the teams that share the same city, grouping by mean
NBA_df = NBA_df.groupby(by='team_only')['W','L'].mean()

NBA_df.reset_index(inplace=True)

#! Now Clean the Cities
def remove_bracket(team):
    if "[" in team:
        return re.findall("([\w\s]*)\[",team)[0]
    else:
        return team

cities['NBA'] = cities.NBA.apply(remove_bracket)
cities = cities [['Metropolitan area', 'Population (2016 est.)[8]','NBA']]
cities.rename(columns={'Metropolitan area':'city', 'Population (2016 est.)[8]':'population', 'NBA':'team_only'}, inplace=True)

merge_df = pd.merge(NBA_df,cities,how='left', on='team_only')
merge_df['win_loss_ratio'] = merge_df.W / (merge_df.W + merge_df.L)
    

    #raise NotImplementedError()

population_by_region = pd.to_numeric(merge_df['population'],errors='coerce') # pass in metropolitan area population from cities
win_loss_by_region = pd.to_numeric(merge_df['win_loss_ratio'],errors='coerce') # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"


stats.pearsonr(population_by_region, win_loss_by_region)[0]

C:\Users\Gamer\AppData\Local\Temp\ipykernel_15000\43111295.py:29: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  NBA_df = NBA_df.groupby(by='team_only')['W','L'].mean()

-0.17657160252844614

## Question 3
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **MLB** using **2018** data.

In [10]:
# Load the databases
MLB_df = pd.read_csv("assets/mlb.csv")
cities = pd.read_html("assets/wikipedia_data.html")[1]
cities = cities.iloc[:-1,[0,3,5,6,7,8]]

MLB_df = MLB_df[MLB_df.year == 2018]
MLB_df = MLB_df[['team', 'W', 'L']]
#Extract the team only
MLB_df['team_only'] = MLB_df.team.apply(lambda x: x.rsplit(None,1)[-1])

#cleaning

MLB_df.loc[1, 'team_only'] = 'Yankees Mets'
MLB_df.loc[18, 'team_only'] = 'Yankees Mets'

MLB_df.loc[13, 'team_only'] = 'Dodgers Angels'
MLB_df.loc[25, 'team_only'] = 'Dodgers Angels'

MLB_df.loc[11, 'team_only'] = 'Giants Athletics'
MLB_df.loc[28, 'team_only'] = 'Giants Athletics'

MLB_df.loc[0, 'team_only'] = 'Red Sox'
MLB_df.loc[3, 'team_only'] = 'Blue Jays'

MLB_df.loc[8, 'team_only'] = 'Cubs White Sox'
MLB_df.loc[21, 'team_only'] = 'Cubs White Sox'
   
#! Now Clean the Cities
def remove_bracket(team):
    if "[" in team:
        return re.findall("([\w\s]*)\[",team)[0]
    else:
        return team

cities['MLB'] = cities.MLB.apply(remove_bracket)
cities = cities [['Metropolitan area', 'Population (2016 est.)[8]','MLB']]
cities.rename(columns={'Metropolitan area':'city', 'Population (2016 est.)[8]':'population', 'MLB':'team_only'}, inplace=True)

MLB_df.W = MLB_df.W.astype(float)
MLB_df.L = MLB_df.L.astype(float)

#The following command is because we need to combine the teams that share the same city, grouping by mean

MLB_df = MLB_df.groupby(by='team_only')['W','L'].mean()

MLB_df.reset_index(inplace=True)
    
merge_df = pd.merge(MLB_df,cities,how='left', on='team_only')
merge_df['win_loss_ratio'] = merge_df.W / (merge_df.W + merge_df.L)

#raise NotImplementedError()

population_by_region = pd.to_numeric(merge_df['population'],errors='coerce') # pass in metropolitan area population from cities
win_loss_by_region = pd.to_numeric(merge_df['win_loss_ratio'],errors='coerce') # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"


stats.pearsonr(population_by_region, win_loss_by_region)[0]

C:\Users\Gamer\AppData\Local\Temp\ipykernel_15000\1285062302.py:44: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  MLB_df = MLB_df.groupby(by='team_only')['W','L'].mean()

0.1505230448710485

### Question 4
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NFL** using **2018** data.

In [11]:
# Load the databases
NFL_df = pd.read_csv("assets/nfl.csv")
cities = pd.read_html("assets/wikipedia_data.html")[1]
cities = cities.iloc[:-1,[0,3,5,6,7,8]]
    
#Starting with cities in this time \\ cleaning

def remove_bracket(team):
    if "[" in team:
        return re.findall("([\w\s]*)\[",team)[0]
    else:
        return team

cities['NFL'] = cities.NFL.apply(remove_bracket)
cities = cities [['Metropolitan area', 'Population (2016 est.)[8]','NFL']]
cities.rename(columns={'Metropolitan area':'city', 'Population (2016 est.)[8]':'population', 'NFL':'team_only'}, inplace=True)

#Now with the NFL dataframe
NFL_df = NFL_df[NFL_df['year']==2018]
NFL_df = NFL_df[['team','W','L']]
    
#Cleaning the names of the team
NFL_df['team'] = NFL_df['team'].str.replace('*', '').str.replace('+', '')
NFL_df = NFL_df[~NFL_df['team'].str.contains('NFC|AFC')] # removing all who say NFC or AFC in the name

NFL_df['team_only'] = NFL_df['team'].apply(lambda x: x.rsplit(None, 1)[-1])
NFL_df.reset_index(inplace=True)
NFL_df.drop('index', axis=1, inplace=True)
    
NFL_df.loc[3, 'team_only'] = 'Giants Jets'
NFL_df.loc[19, 'team_only'] = 'Giants Jets'

NFL_df.loc[28, 'team_only'] = 'Rams Chargers'
NFL_df.loc[13, 'team_only'] = 'Rams Chargers'

NFL_df.loc[30, 'team_only'] = '49ers Raiders'
NFL_df.loc[15, 'team_only'] = '49ers Raiders'
    
NFL_df.W = NFL_df.W.astype(float)
NFL_df.L = NFL_df.L.astype(float)

NFL_df = NFL_df.groupby(by='team_only')['W','L'].mean()

NFL_df.reset_index(inplace=True)
merge_df = pd.merge(NFL_df,cities,how='left', on='team_only')
merge_df['win_loss_ratio'] = merge_df.W / (merge_df.W + merge_df.L)



#raise NotImplementedError()
    
population_by_region = pd.to_numeric(merge_df['population'],errors='coerce') # pass in metropolitan area population from cities
win_loss_by_region = pd.to_numeric(merge_df['win_loss_ratio'],errors='coerce') # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]
assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"


stats.pearsonr(population_by_region, win_loss_by_region)[0]

C:\Users\Gamer\AppData\Local\Temp\ipykernel_15000\1572520594.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  NFL_df['team'] = NFL_df['team'].str.replace('*', '').str.replace('+', '')
C:\Users\Gamer\AppData\Local\Temp\ipykernel_15000\1572520594.py:42: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  NFL_df = NFL_df.groupby(by='team_only')['W','L'].mean()

0.00492211214934943